export { default as DesktopNavBar } from "./navbar/desktop";
export { default as MobileNavBar } from "./navbar/mobile";
export { default as Intro } from "./intro";
export { default as Services } from "./servicess";
export { default as AboutMe } from "./about-me";
export { default as WorkHistory } from "./work-history";
export { default as Projects } from "./projects";
export { default as ContactMe } from "./contact-me";
export { default as Footer } from "./footer";
